/// MongoDB shell 关键字（与 [bytebase/gomongo](https://github.com/bytebase/gomongo) 对齐）。
/// 命令侧只保留 **读 / 写** 两套；其余字面量、BSON、`$` 阶段等并入 [mongoOtherKeywords]。
/// 与 [KeyWordTokenBuilder] 一致：标识符转大写后匹配。

/// 读：含 `db` 级、`db.<集合>` 级、以及 `find(...)` 后的游标链（sort、limit 等）
const Set<String> mongoReadCommands = {
  'SHOW',
  'DBS',
  'DATABASES',
  'COLLECTIONS',
  'TABLES',
  'VERSION',
  'SERVERSTATUS',
  'SERVERBUILDINFO',
  'HOSTINFO',
  'LISTCOMMANDS',
  'STATS',
  'GETCOLLECTIONNAMES',
  'GETCOLLECTIONINFOS',
  'FIND',
  'FINDONE',
  'AGGREGATE',
  'COUNT',
  'COUNTDOCUMENTS',
  'ESTIMATEDDOCUMENTCOUNT',
  'DISTINCT',
  'GETINDEXES',
  'DATASIZE',
  'STORAGESIZE',
  'TOTALINDEXSIZE',
  'TOTALSIZE',
  'ISCAPPED',
  'LATENCYSTATS',
  'VALIDATE',
  'HINT',
  'LIMIT',
  'MAX',
  'MIN',
  'PRETTY',
  'PROJECTION',
  'SKIP',
  'SORT',
};

/// 写：含 `db` 级与 `db.<集合>` 级变更
const Set<String> mongoWriteCommands = {
  'DROPDATABASE',
  'CREATECOLLECTION',
  'INSERTONE',
  'INSERTMANY',
  'UPDATEONE',
  'UPDATEMANY',
  'REPLACEONE',
  'DELETEONE',
  'DELETEMANY',
  'FINDONEANDUPDATE',
  'FINDONEANDREPLACE',
  'FINDONEANDDELETE',
  'CREATEINDEX',
  'CREATEINDEXES',
  'DROPINDEX',
  'DROPINDEXES',
  'DROP',
  'RENAMECOLLECTION',
  'REMOVE',
};

/// 非命令读写的杂项高亮：字面量、`db`/`show`、BSON 构造、管道、`$expr` 逻辑
const Set<String> mongoOtherKeywords = {
  'TRUE',
  'FALSE',
  'NULL',
  'DB',
  'DATE',
  'DECIMAL128',
  'DOUBLE',
  'INT32',
  'ISODATE',
  'LONG',
  'NUMBERDECIMAL',
  'NUMBERINT',
  'NUMBERLONG',
  'OBJECTID',
  'TIMESTAMP',
  'UUID',
  r'$ADDFIELDS',
  r'$BUCKET',
  r'$BUCKETAUTO',
  r'$COLLSTATS',
  r'$COUNT',
  r'$CURRENTOP',
  r'$DENSIFY',
  r'$DOCUMENTS',
  r'$FACET',
  r'$FILL',
  r'$GEONEAR',
  r'$GRAPHLOOKUP',
  r'$GROUP',
  r'$INDEXSTATS',
  r'$LIMIT',
  r'$LOOKUP',
  r'$MATCH',
  r'$MERGE',
  r'$OUT',
  r'$PROJECT',
  r'$REDACT',
  r'$REPLACEROOT',
  r'$REPLACEWITH',
  r'$SAMPLE',
  r'$SEARCH',
  r'$SET',
  r'$SETWINDOWFIELDS',
  r'$SKIP',
  r'$SORT',
  r'$SORTBYCOUNT',
  r'$UNIONWITH',
  r'$UNSET',
  r'$UNWIND',
  'AND',
  'NOT',
  'OR',
};

final Set<String> keywords = {
  ...mongoReadCommands,
  ...mongoWriteCommands,
  ...mongoOtherKeywords,
};
