// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'mssql.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `base_0001_01_01`, `base_1900_01_01`, `column_type_to_u8`, `date_to_epoch_millis`, `datetime2_to_epoch_millis`, `datetime_to_epoch_millis`, `datetimeoffset_to_epoch_millis`, `smalldatetime_to_epoch_millis`, `time_to_millis_since_midnight`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `from_column`, `from_columndata`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ConnWrapper>>
abstract class ConnWrapper implements RustOpaqueInterface {
  Future<void> close();

  static Future<ConnWrapper> open({required String dsn}) =>
      RustLib.instance.api.crateApiMssqlConnWrapperOpen(dsn: dsn);

  Stream<QueryStreamItem> query({required String query});
}

class QueryColumn {
  final String name;
  final int columnType;

  const QueryColumn({required this.name, required this.columnType});

  @override
  int get hashCode => name.hashCode ^ columnType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QueryColumn &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          columnType == other.columnType;
}

class QueryHeader {
  final List<QueryColumn> columns;
  final BigInt affectedRows;

  const QueryHeader({required this.columns, required this.affectedRows});

  @override
  int get hashCode => columns.hashCode ^ affectedRows.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QueryHeader &&
          runtimeType == other.runtimeType &&
          columns == other.columns &&
          affectedRows == other.affectedRows;
}

class QueryRow {
  final List<QueryValue> values;

  const QueryRow({required this.values});

  @override
  int get hashCode => values.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QueryRow &&
          runtimeType == other.runtimeType &&
          values == other.values;
}

@freezed
sealed class QueryStreamItem with _$QueryStreamItem {
  const QueryStreamItem._();

  const factory QueryStreamItem.header(QueryHeader field0) =
      QueryStreamItem_Header;
  const factory QueryStreamItem.row(QueryRow field0) = QueryStreamItem_Row;
  const factory QueryStreamItem.error(String field0) = QueryStreamItem_Error;
}

@freezed
sealed class QueryValue with _$QueryValue {
  const QueryValue._();

  const factory QueryValue.null_() = QueryValue_NULL;
  const factory QueryValue.bytes(Uint8List field0) = QueryValue_Bytes;
  const factory QueryValue.int(PlatformInt64 field0) = QueryValue_Int;
  const factory QueryValue.uInt(BigInt field0) = QueryValue_UInt;
  const factory QueryValue.float(double field0) = QueryValue_Float;
  const factory QueryValue.double(double field0) = QueryValue_Double;
  const factory QueryValue.dateTime(PlatformInt64 field0) = QueryValue_DateTime;
}
