/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package oracle */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "oracle.go"

#include <stdint.h>
#include <stdlib.h>

typedef struct oracle_query_value_t {
  int32_t kind;
  int64_t int_value;
  uint64_t uint_value;
  float float_value;
  double double_value;
  int64_t datetime_value;
  uint8_t* bytes_value;
  int32_t bytes_len;
} oracle_query_value_t;

typedef struct oracle_query_row_t {
  oracle_query_value_t* values;
  int32_t value_count;
} oracle_query_row_t;

typedef struct oracle_query_column_t {
  char* name;
  char* column_type;
} oracle_query_column_t;

typedef struct oracle_query_header_t {
  oracle_query_column_t* columns;
  int32_t column_count;
  int64_t affected_rows;
} oracle_query_header_t;

typedef struct oracle_query_batch_t {
  oracle_query_row_t* rows;
  int32_t row_count;
  int32_t done;
} oracle_query_batch_t;

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern int64_t oracle_open(char* dsn, char** errOut);
extern void oracle_close(int64_t handle);
extern int64_t oracle_query_open(int64_t handle, char* sqlText, char** errOut);
extern void oracle_query_close(int64_t queryHandle);
extern oracle_query_header_t* oracle_query_header(int64_t queryHandle, char** errOut);
extern oracle_query_batch_t* oracle_query_next_batch(int64_t queryHandle, int32_t batchSize, char** errOut);
extern void oracle_query_free_header(oracle_query_header_t* header);
extern void oracle_query_free_batch(oracle_query_batch_t* batch);
extern void oracle_free_string(char* s);

#ifdef __cplusplus
}
#endif
